apiVersion: v1
kind: Pod
metadata:
  name: hook-demo
spec:
  containers:
    - name: hook-demo
      image: coolgourav147/nginx-custom
      ports:
       - containerPort: 9090
      lifecycle:
         postStart:
           exec:
              command: ["/bin/sh","c","date >> /container-postStart.txt"]
         preStop:
           exec:
             command: ["/usr/sbin/nginx"]
 #terminationGracePeriodSecond: 30