apiVersion: v1
kind: Pod
metadata:
  name: postgres2
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: oldpassword
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: PG_PASS

#here The second definition of the POSTGRES_PASSWORD overrides the value using the PG_PASS value from the postgres-secret resource.
#https://www.baeldung.com/linux/kubernetes-pod-environment-variables
