apiVersion: v1
kind: Pod
metadata:
  name: postgres1
spec:
  containers:
  - name: postgres1
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: oldpassword
    - name: POSTGRES_PASSWORD
      value: newpassword
