apiVersion: v1
kind: ReplicationController
metadata:
    name: firstreplica
    labels:
      appname: votingapp
spec:
  replicas: 5
  template:
     metadata:
          name: firstpod
          labels:
             env: dev
             type: dev
     spec:
       containers:
           - name: firstpod
             image: coolgourav147/nginx-custom