apiVersion: v1
kind: Pod
metadata:
     name: cmdpod
     labels:
        env: dev
        dev: dev
spec:
  containers:
      - name: cmdcontainer
        image: coolgourav147/nginx-custom
        env:
          - name: MY_DEMO
            value: password
        args: ["sleep","30"]