server:
  port: 8081

spring:
  application:
    name: course-service

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: ${datasource.dialect}
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode : true
  show-sql: true
  hibernate:
    ddl_auto: none

